# Generated by Django 4.1.4 on 2023-02-06 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('control_num', models.UUIDField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('R', 'Under Review'), ('D', 'Deleted')], default='A', max_length=2)),
                ('notes', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('CE', 'Community Environment'), ('HE', 'Health Seeking Behaviour'), ('HH', 'Household Data'), ('SI', 'Social Inclusion')], max_length=2)),
                ('answer_type', models.CharField(choices=[('CH', 'Choice Field'), ('FL', 'Floating Point Number Field'), ('FT', 'Free Type Field'), ('MC', 'Multiple Choice Field'), ('MT', 'Multiple Choice Text Field'), ('NB', 'Number Field'), ('TX', 'Text Field')], max_length=2)),
                ('question_body', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('HP', 'Home Phone'), ('CP', 'Cell Phone'), ('WK', 'Work Phone')], default='CP', max_length=2)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('control_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.patientrecord')),
            ],
        ),
        migrations.CreateModel(
            name='PatientBio',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=2)),
                ('nationality', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('control_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.patientrecord')),
            ],
        ),
        migrations.CreateModel(
            name='NOK',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('control_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.patientrecord')),
            ],
        ),
        migrations.CreateModel(
            name='HouseholdInfo',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('marital_status', models.CharField(choices=[('SI', 'Single'), ('MR', 'Married'), ('DI', 'Divorced'), ('WI', 'Widowed'), ('CL', 'Common-Law')], default='SI', max_length=2)),
                ('number_of_children', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('control_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.patientrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('PR', 'Permanent'), ('TM', 'Temporary'), ('CT', 'Contract'), ('UE', 'Unemployed')], default='PR', max_length=2)),
                ('employer', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('control_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.patientrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('PE', 'Personal Email'), ('BE', 'Business Email'), ('WK', 'Work Email')], default='PE', max_length=2)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('control_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.patientrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('sex', models.CharField(max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('control_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.patientrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('HM', 'Home Address'), ('ML', 'Mailing Address'), ('TM', 'Temporary Address'), ('WK', 'Work Address')], default='HM', max_length=2)),
                ('line1', models.CharField(max_length=150)),
                ('line2', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('postal_code', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('control_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.patientrecord')),
            ],
        ),
    ]
