# Generated by Django 4.1.4 on 2023-02-06 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.patientrecord')),
            ],
        ),
        migrations.RenameModel(
            old_name='NOK',
            new_name='NextOfKin',
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('CH', 'Choice Field'), ('FL', 'Floating Point Number Field'), ('FT', 'Free Type Text Field'), ('MC', 'Multiple Choice Field'), ('MT', 'Multiple Choice Text Field'), ('NB', 'Number Field'), ('TX', 'Text Field')], max_length=2),
        ),
        migrations.CreateModel(
            name='Float',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backoffice.answer')),
                ('body', models.FloatField()),
            ],
            bases=('backoffice.answer',),
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backoffice.answer')),
                ('body', models.IntegerField()),
            ],
            bases=('backoffice.answer',),
        ),
        migrations.CreateModel(
            name='ShortText',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backoffice.answer')),
                ('body', models.CharField(max_length=255)),
            ],
            bases=('backoffice.answer',),
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backoffice.answer')),
                ('body', models.TextField()),
            ],
            bases=('backoffice.answer',),
        ),
        migrations.AddField(
            model_name='answer',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.question'),
        ),
    ]
